/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    StealthAnnouncer: {
      address:
        "0x7b4889d9d01a8f64cb677345fc06bda58184c46bf9a1b46fab323d142b18577",
      abi: [
        {
          type: "impl",
          name: "StealthAnnouncerImpl",
          interface_name: "contracts::stealth_announcer::IStealthAnnouncer",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::stealth_announcer::IStealthAnnouncer",
          items: [
            {
              type: "function",
              name: "announce",
              inputs: [
                {
                  name: "ephemeral_pub_x",
                  type: "core::felt252",
                },
                {
                  name: "ephemeral_pub_y",
                  type: "core::felt252",
                },
                {
                  name: "stealth_commitment",
                  type: "core::felt252",
                },
                {
                  name: "view_tag",
                  type: "core::felt252",
                },
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_announcer::StealthAnnouncer::Announcement",
          kind: "struct",
          members: [
            {
              name: "view_tag",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "stealth_commitment",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "ephemeral_pub_x",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "ephemeral_pub_y",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "token",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "caller",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_announcer::StealthAnnouncer::Event",
          kind: "enum",
          variants: [
            {
              name: "Announcement",
              type: "contracts::stealth_announcer::StealthAnnouncer::Announcement",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x6453486871b45f745d8bb13f569130147239ec7de91a4fd46e7b22b827c16a9",
    },
    StealthRegistry: {
      address:
        "0x3fc97833306e586a1d1e7d0a40d03217fc4a806b8012b91b3bafb8a13c5b6d1",
      abi: [
        {
          type: "impl",
          name: "StealthRegistryImpl",
          interface_name: "contracts::stealth_registry::IStealthRegistry",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::stealth_registry::IStealthRegistry",
          items: [
            {
              type: "function",
              name: "register",
              inputs: [
                {
                  name: "spend_pub_x",
                  type: "core::felt252",
                },
                {
                  name: "view_pub_x",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_meta_address",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "(core::felt252, core::felt252)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_registered",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_registry::StealthRegistry::MetaAddressRegistered",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "spend_pub_x",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "view_pub_x",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_registry::StealthRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "MetaAddressRegistered",
              type: "contracts::stealth_registry::StealthRegistry::MetaAddressRegistered",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x932fbd6fb89b5681af368e008f24fdfc08041ef4b8470a5646504485de9292",
    },
    StealthPay: {
      address:
        "0x7223a789c1f9fe9baf3ab9f123bc11dadb55849a98c5b57c64d184256b876c8",
      abi: [
        {
          type: "impl",
          name: "StealthPayImpl",
          interface_name: "contracts::stealth_pay::IStealthPay",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::stealth_pay::IStealthPay",
          items: [
            {
              type: "function",
              name: "send",
              inputs: [
                {
                  name: "stealth_commitment",
                  type: "core::felt252",
                },
                {
                  name: "ephemeral_pub_x",
                  type: "core::felt252",
                },
                {
                  name: "ephemeral_pub_y",
                  type: "core::felt252",
                },
                {
                  name: "view_tag",
                  type: "core::felt252",
                },
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "claim",
              inputs: [
                {
                  name: "stealth_commitment",
                  type: "core::felt252",
                },
                {
                  name: "stealth_pub_x",
                  type: "core::felt252",
                },
                {
                  name: "signature_r",
                  type: "core::felt252",
                },
                {
                  name: "signature_s",
                  type: "core::felt252",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_deposit",
              inputs: [
                {
                  name: "commitment",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "(core::starknet::contract_address::ContractAddress, core::integer::u256, core::starknet::contract_address::ContractAddress, core::bool)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_announcer",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "announcer_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_pay::StealthPay::PaymentSent",
          kind: "struct",
          members: [
            {
              name: "commitment",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "token",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "sender",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_pay::StealthPay::PaymentClaimed",
          kind: "struct",
          members: [
            {
              name: "commitment",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_pay::StealthPay::Event",
          kind: "enum",
          variants: [
            {
              name: "PaymentSent",
              type: "contracts::stealth_pay::StealthPay::PaymentSent",
              kind: "nested",
            },
            {
              name: "PaymentClaimed",
              type: "contracts::stealth_pay::StealthPay::PaymentClaimed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x7aca503a238fed048bf58ea323a917872f88e1c155eb8ead2f583357ebcf440",
    },
  },
  sepolia: {
    StealthAnnouncer: {
      address:
        "0x71bd0f74c0ee290937ed687b5d8da9cc7b3d70ba2df1161492b74d5022b98dc",
      abi: [
        {
          type: "impl",
          name: "StealthAnnouncerImpl",
          interface_name: "contracts::stealth_announcer::IStealthAnnouncer",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::stealth_announcer::IStealthAnnouncer",
          items: [
            {
              type: "function",
              name: "announce",
              inputs: [
                {
                  name: "ephemeral_pub_x",
                  type: "core::felt252",
                },
                {
                  name: "ephemeral_pub_y",
                  type: "core::felt252",
                },
                {
                  name: "stealth_commitment",
                  type: "core::felt252",
                },
                {
                  name: "view_tag",
                  type: "core::felt252",
                },
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_announcer::StealthAnnouncer::Announcement",
          kind: "struct",
          members: [
            {
              name: "view_tag",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "stealth_commitment",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "ephemeral_pub_x",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "ephemeral_pub_y",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "token",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "caller",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_announcer::StealthAnnouncer::Event",
          kind: "enum",
          variants: [
            {
              name: "Announcement",
              type: "contracts::stealth_announcer::StealthAnnouncer::Announcement",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x4c8bba7722ee2c85fde9ed22704319fe77a42bb635a49856f3574b1a95fc14a",
    },
    StealthRegistry: {
      address:
        "0x166f89e2e9b0499a28fbde2dc754c72ca986456101cc5481b301d4724d3495c",
      abi: [
        {
          type: "impl",
          name: "StealthRegistryImpl",
          interface_name: "contracts::stealth_registry::IStealthRegistry",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::stealth_registry::IStealthRegistry",
          items: [
            {
              type: "function",
              name: "register",
              inputs: [
                {
                  name: "spend_pub_x",
                  type: "core::felt252",
                },
                {
                  name: "view_pub_x",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_meta_address",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "(core::felt252, core::felt252)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_registered",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_registry::StealthRegistry::MetaAddressRegistered",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "spend_pub_x",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "view_pub_x",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_registry::StealthRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "MetaAddressRegistered",
              type: "contracts::stealth_registry::StealthRegistry::MetaAddressRegistered",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x5a2bcf916f45751f6bff858ad7e10cb85e5153e8238383c9d4fcd40ebaaffde",
    },
    StealthPay: {
      address:
        "0x7e16306f400c178dea90be2d01460cd217d655b07af495e1049a51ae323585a",
      abi: [
        {
          type: "impl",
          name: "StealthPayImpl",
          interface_name: "contracts::stealth_pay::IStealthPay",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::stealth_pay::IStealthPay",
          items: [
            {
              type: "function",
              name: "send",
              inputs: [
                {
                  name: "stealth_commitment",
                  type: "core::felt252",
                },
                {
                  name: "ephemeral_pub_x",
                  type: "core::felt252",
                },
                {
                  name: "ephemeral_pub_y",
                  type: "core::felt252",
                },
                {
                  name: "view_tag",
                  type: "core::felt252",
                },
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "claim",
              inputs: [
                {
                  name: "stealth_commitment",
                  type: "core::felt252",
                },
                {
                  name: "stealth_pub_x",
                  type: "core::felt252",
                },
                {
                  name: "signature_r",
                  type: "core::felt252",
                },
                {
                  name: "signature_s",
                  type: "core::felt252",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_deposit",
              inputs: [
                {
                  name: "commitment",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "(core::starknet::contract_address::ContractAddress, core::integer::u256, core::starknet::contract_address::ContractAddress, core::bool)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_announcer",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "announcer_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_pay::StealthPay::PaymentSent",
          kind: "struct",
          members: [
            {
              name: "commitment",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "token",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "sender",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_pay::StealthPay::PaymentClaimed",
          kind: "struct",
          members: [
            {
              name: "commitment",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::stealth_pay::StealthPay::Event",
          kind: "enum",
          variants: [
            {
              name: "PaymentSent",
              type: "contracts::stealth_pay::StealthPay::PaymentSent",
              kind: "nested",
            },
            {
              name: "PaymentClaimed",
              type: "contracts::stealth_pay::StealthPay::PaymentClaimed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x182b23fcb96ab5756b08d206b704ab281598cc2504df163588b03fdb403b482",
    },
  },
} as const;

export default deployedContracts;
